apiVersion: v1
kind: Secret
metadata:
  name: gitlab-credentials
  namespace: crossplane-system
type: Opaque
data:
  token: Z2xwYXQtYnhGTXlVaDhCMzM5YzVkX015eTQK # Replace with your GitLab Personal Access Token, base64 encoded
