apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: AccessToken
metadata:
  name: example-access-token
spec:
  forProvider:
    name: "my-token"
    accessLevel: 20
    groupIdRef:
      name: group-one
    scopes:
      - "read_repository"
    expiresAt: "2026-04-01T00:00:00Z"
  providerConfigRef:
    name: provider-gitlab-config
  writeConnectionSecretToRef:
    name: gitlab-example-access-token
    namespace: crossplane-system
