apiVersion: gitlab.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-gitlab-config
spec:
  baseURL: http://gitlab-webservice-default.gitlab.svc.cluster.local:8080 # Check this
  credentials:
    method: PersonalAccessToken
    secretRef:
      key: token
      name: gitlab-credentials
      namespace: crossplane-system
    source: Secret
