apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - name: 1-nginx
      - name: 2-nginx
      - name: 3-nginx
      - name: 4-nginx
      - name: 5-nginx
      - name: 6-nginx
  template:
    metadata:
      name: '{{.name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/raweber42/kubernetes-sandbox.git
        targetRevision: main
        path: charts/nginx/
        helm:
          valuesObject:
            name: '{{.name}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
