apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: example-provider-secret
type: Opaque
stringData:
  credentials: |
    {
      "url": "http://harbor-core.harbor.svc.cluster.local",
      "username": "admin",
      "password": "password"
    }
---
apiVersion: harbor.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: harbor 
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: example-provider-secret
      key: credentials
