argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: true
  global:
    domain: argocd.local
  server:
    extraArgs:
      - --insecure
    ingress:
      enabled: true
      controller: generic
      ingressClassName: traefik
      hostname: argocd.local
      path: /
  configs:
    cm:
      application.resourceTrackingMethod: "annotation+label"
